name: Pull Request Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
